name: 'Slack Notification'
description: 'Permission-aware RAG System用のSlack通知アクション'
author: 'NetApp Japan Technology Team'

inputs:
  type:
    description: '通知タイプ (test, deploy, quality, error)'
    required: true
  data:
    description: '通知データ (JSON形式)'
    required: true
  webhook-url:
    description: 'Slack Webhook URL'
    required: true
  channel:
    description: 'Slack チャンネル'
    required: false
    default: '#ci-cd'
  username:
    description: 'Bot ユーザー名'
    required: false
    default: 'RAG-CI/CD-Bot'
  icon-emoji:
    description: 'Bot アイコン'
    required: false
    default: ':robot_face:'

outputs:
  success:
    description: '通知送信成功フラグ'
    value: ${{ steps.notify.outputs.success }}
  message:
    description: '送信されたメッセージ'
    value: ${{ steps.notify.outputs.message }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Send Slack notification
      id: notify
      shell: bash
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook-url }}
        SLACK_CHANNEL: ${{ inputs.channel }}
        SLACK_USERNAME: ${{ inputs.username }}
        SLACK_ICON_EMOJI: ${{ inputs.icon-emoji }}
      run: |
        # Slack通知スクリプトの実行
        if python scripts/ci/slack-notifier.py --type "${{ inputs.type }}" --data '${{ inputs.data }}'; then
          echo "success=true" >> $GITHUB_OUTPUT
          echo "message=Slack notification sent successfully" >> $GITHUB_OUTPUT
          echo "✅ Slack通知送信成功"
        else
          echo "success=false" >> $GITHUB_OUTPUT
          echo "message=Failed to send Slack notification" >> $GITHUB_OUTPUT
          echo "❌ Slack通知送信失敗"
          exit 1
        fi

branding:
  icon: 'message-circle'
  color: 'blue'